# Generated by Django 4.0.4 on 2022-05-24 19:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('late_fee_per_day', models.FloatField(default=0)),
                ('payment_date', models.DateField()),
            ],
        ),
    ]
