# Generated by Django 4.0.4 on 2022-05-24 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("payments", "0001_initial"),
        ("rentals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="rental",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rentals.rental",
            ),
        ),
    ]
