# Generated by Django 4.0.4 on 2022-05-30 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='rental',
        ),
    ]
