# Generated by Django 4.0.4 on 2022-05-30 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0004_rental_payment"),
        ("payments", "0004_remove_payment_rental"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="rental",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="rentals.rental",
            ),
        ),
    ]
