# Generated by Django 4.0.4 on 2022-05-30 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_payment_rental"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="rental",
        ),
    ]
