# Generated by Django 4.0.4 on 2022-05-24 19:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rental_date', models.DateField(auto_now_add=True)),
                ('planned_return_date', models.DateField()),
                ('return_date', models.DateField(default=None)),
                ('media', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='medias.media')),
            ],
        ),
    ]
