# Generated by Django 4.0.4 on 2022-05-30 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_payment_rental'),
        ('rentals', '0003_alter_rental_planned_return_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='payment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.payment'),
        ),
    ]
