# Generated by Django 4.0.4 on 2022-05-30 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_payment_rental"),
        ("rentals", "0004_rental_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rental",
            name="payment",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rentals",
                to="payments.payment",
            ),
        ),
    ]
