# Generated by Django 4.0.4 on 2022-06-01 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_remove_payment_rental"),
        ("rentals", "0005_alter_rental_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rental",
            name="payment",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.payment",
            ),
        ),
        migrations.AlterField(
            model_name="rental",
            name="return_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
